version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pos_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_saas_pro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: pos_api
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/pos_saas_pro"
      JWT_SECRET: "your_jwt_secret_here"
    ports:
      - "3000:3000"
    restart: always

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://pos-cerebrodigital.com.mx/api
    container_name: pos_web

    depends_on:
      - api
    ports:
      - "3012:3001"
    restart: always

volumes:
  mysql_data:
